### ISSUE TITLE
Operator cannot be applied to operands of type 'System.Windows.Thickness' and 'double'

### ISSUE THREAD

**Issue by Tum4ik** [hexinnovation/MathConverter#5]
Tried with "+" and "/" operators... Probable the same problem exists for other operators.
```xaml
Padding="{Binding SomePadding, ElementName=SomeElement, Converter={StaticResource MathConverter}, ConverterParameter=x/4;x/4;x/4;x/4}"
Padding="{Binding SomePadding, ElementName=SomeElement, Converter={StaticResource MathConverter}, ConverterParameter=x/4}"
```
Both variants do not work.

**Comment by Tum4ik** [comment]
BTW: for CornerRadius I also have that problem.

**Comment by timothylcooke** [comment]
I mean it makes sense that that operator doesn't work. There is no C# "/" operator between Thickness and double. This doesn't feel like a bug as much as it is a "You can't do this conversion this way."

**Technical details you probably don't care about:**

Effectively, MathConverter is a very simplified C# compiler, which dynamically parses and evaluates your conversion string using reflection. The difference is that the compilation happens at runtime, so effectively, you're getting a "compiler error" at runtime that states that there's no available operator, in the same way that this C# code would not compile:

```
Thickness x = SomeElement.SomePadding;
return x / 4; // Compiler error CS0019: Operator '/' cannot be applied to operands of type 'Thickness' and 'int'
```

It's a little more complicated than this. Technically, your "x/4" (or "x/4;x/4;x/4;x/4") expression compiles and the particular operator to call is determined at conversion time, and therefore varies based on the particular arguments the operator is evaluated with. In this case, it means the operator varies based on the type of the data you're binding to.

**What you actually need to know:**

If you know that the Padding on SomeElement is guaranteed to be the same for LTRB:
You can simply bind to the Left (or Top, etc.) Padding instead of the full Padding object. Left property is a double, and there is a built-in "/" operator for double and double:
```
Padding="{Binding SomePadding.Left, ElementName=SomeElement, Converter={StaticResource MathConverter}, ConverterParameter=x/4}"
```

If you can't guarantee that, you can do it with a multibinding where you divide each side by four.

```
<WhateverControl>
    <WhateverControl.Padding>
        <MultiBinding ConverterParameter="x/4;y/4;z/4;[3]/4" Converter="{StaticResource MathConverter}">
            <Binding Path="SomePadding.Left" ElementName="SomeElement" />
            <Binding Path="SomePadding.Top" ElementName="SomeElement" />
            <Binding Path="SomePadding.Right" ElementName="SomeElement" />
            <Binding Path="SomePadding.Bottom" ElementName="SomeElement" />
        </MultiBinding>
    </WhateverControl.Padding>
</WhateverControl>
```

The same general principles would apply for CornerRadius (though property names are TopLeft, TopRight, etc.) and would work for +, -, and * operators.

Hopefully this helps 🙂
